In [ ]:
#create any 3 dimensional array and practice indexing
import numpy as np
b = np.array([[[0, 1, 2], [3, 4, 5],[2,4,6]]])
b

array([[[0, 1, 2],
        [3, 4, 5],
        [2, 4, 6]]])

In [ ]:
#create array of suqares of keys of below dictionary
d = {1:2,2:3,3:4,4:5}
keys = [1,2,3,4,5]
square = [i**2 for i in keys]
array = np.array(square)
array


array([ 1,  4,  9, 16, 25])

In [ ]:
# multiply any 2 dim array to identity matrix (2*2) and comment on result
arr_1 =np.array([[1,1,2],[2,3,4]])
arr_2 =np.array([[2,3,4],[4,5,6]])
arr_3 = arr_1*arr_2
arr_3

array([[ 2,  3,  8],
       [ 8, 15, 24]])